sonarr_url: 'http://localhost:8989/sonarr/api/v3'
sonarr_api_key: 'YOUR_SONARR_API_KEY'

future_days: 60
skip_unmonitored: true

collection_name: "New Season Airing Soon"
sort_title: "New Season Soon"
capitalize_dates: true

backdrop:
  back_color: "#81007F"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20

text:
  date_format: "ddd dd/mm"      # e.g., "yyyy-mm-dd", "mm/dd", "dd/mm", etc.
  use_text: "NEW SEASON"    # e.g. "SEASON PREMIERES" or "NEW SEASON"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"
